spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003172
  
server:
  port: 9090
  
logging:
  file: /var/log/adminserver/apollo-adminservice.log
