spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}

server:
  port: 8080
  
logging:
  file: /var/log/portal/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


